import { ArrowRight, Check, FileText, ShieldCheck, Sparkles } from "lucide-react"
import { CtaButton } from "../shared/cta-button"
import { Footer } from "../shared/footer"
import { Header } from "../shared/header"
import { Section } from "../shared/section"
import { brandStyles, sharedStyles } from "../shared/tokens"

const products = [
  { id: "focus-guide", title: "The Focus & Consistency Guide", price: "₹499", body: "A practical system for protecting your attention, choosing your priorities, and building consistency without overcomplicating your day.", features: ["Daily focus framework", "Simple consistency tracker", "Distraction reset plan", "Practical prompts for weekly review"] },
  { id: "career-guide", title: "The Career Clarity Guide", price: "₹499", body: "A decision framework for people who feel stuck between options and need a clearer next move.", features: ["Decision clarity framework", "Option comparison prompts", "Skill and direction audit", "Next-action worksheet"] },
  { id: "business-guide", title: "The Business Action Guide", price: "₹499", body: "A focused guide for turning an idea into a problem, offer, test, and simple action plan.", features: ["Problem-to-offer framework", "Simple validation checklist", "Action planning template", "Weekly execution review"] },
]

export default function SalesPage() {
  return <main className="me-page" id="top"><style>{brandStyles + sharedStyles + styles}</style>
    <Header links={[{ label: "The offer", href: "#offer" }, { label: "What you get", href: "#included" }, { label: "Questions", href: "#faq" }]} loginHref="/quiz" cta={{ label: "Choose a guide", href: "#offer" }} />
    <Section className="gb-sales-hero"><div className="me-wrap"><p className="me-eyebrow">Growth Believer resources</p><h1>Practical guides for the problem you want to solve next.</h1><p>Choose one focused digital resource. Use it to understand the problem, make a clearer plan, and take action.</p><CtaButton href="#offer" variant="violet">CHOOSE YOUR RESOURCE</CtaButton><div className="gb-trust"><span><Sparkles aria-hidden="true" />Focused, practical content</span><span><ShieldCheck aria-hidden="true" />Digital access</span><span><FileText aria-hidden="true" />Built to use, not just read</span></div></div></Section>

    <Section id="offer" className="gb-offer"><div className="me-wrap"><div className="me-section-heading"><p className="me-eyebrow">Choose your starting point</p><h2>One problem. One useful guide.</h2><p>Start with the resource that matches the area you want to work on now.</p></div><div className="gb-offer-grid">{products.map((product) => <article id={product.id} key={product.id}><span className="gb-product-label">Digital guide</span><h3>{product.title}</h3><p>{product.body}</p><div className="gb-price"><strong>{product.price}</strong><small>One-time digital product</small></div><ul>{product.features.map((feature) => <li key={feature}><Check aria-hidden="true" />{feature}</li>)}</ul><CtaButton href={`/order-form?product=${product.id}`} variant="violet">GET THIS GUIDE</CtaButton></article>)}</div></div></Section>

    <Section id="included" className="gb-included"><div className="me-wrap"><div className="gb-included-grid"><div><p className="me-eyebrow">What makes it useful</p><h2>Built for action, not information overload.</h2><p>Each guide is organized around a real problem and a simple sequence you can follow.</p></div><div className="gb-included-list"><article><b>01</b><div><h3>Understand</h3><p>See the problem clearly before you try to fix it.</p></div></article><article><b>02</b><div><h3>Plan</h3><p>Choose a small, realistic approach that fits your situation.</p></div></article><article><b>03</b><div><h3>Act</h3><p>Turn the idea into a next action you can actually complete.</p></div></article></div></div></div></Section>

    <Section className="gb-why-buy"><div className="me-wrap"><div className="gb-buy-card"><div><p className="me-eyebrow">Why Growth Believer</p><h2>You already have enough advice. Use something you can act on.</h2><p>Growth Believer turns broad growth topics into focused resources with clear steps, prompts, and tools.</p></div><CtaButton href="/quiz" variant="ghost">NOT SURE? TAKE THE ASSESSMENT</CtaButton></div></div></Section>

    <Section id="faq" className="gb-faq"><div className="me-wrap"><div className="me-section-heading"><p className="me-eyebrow">Questions</p><h2>Before you choose</h2></div><div className="gb-faq-list"><details><summary>What do I receive?</summary><p>You receive the selected digital guide and its included worksheets or prompts. The order flow in this MVP collects your details and then confirms the request.</p></details><details><summary>Is this a course or coaching program?</summary><p>No. These are focused digital resources designed for self-guided use.</p></details><details><summary>Which guide should I choose?</summary><p>Choose the guide that matches the problem you want to work on first. If you are unsure, take the free Growth Assessment.</p></details><details><summary>Does the checkout process payment?</summary><p>This MVP order flow does not process card or payment details. It records the selected product and your order details so the next delivery step can be connected later.</p></details></div></div></Section>
    <Footer columns={[{ heading: "Resources", links: ["Products", "Growth Assessment", "Guides"] }, { heading: "Growth", links: ["Productivity", "Mindset", "Career", "Business"] }]} detail="Focused digital resources for making real progress." />
  </main>
}

const styles = `
.gb-sales-hero{padding:clamp(5rem,3rem + 7vw,8.5rem) 0 var(--me-section);background:radial-gradient(60% 90% at 76% 0,#3a348f,transparent 68%),var(--me-bg-deep)}.gb-sales-hero .me-wrap{max-width:60rem;text-align:center}.gb-sales-hero h1{max-width:15ch;margin:1rem auto 0;font-size:clamp(2.5rem,1.2rem + 4.6vw,4.7rem);font-weight:600;letter-spacing:-.05em;line-height:1.03}.gb-sales-hero>div>p:not(.me-eyebrow){max-width:56ch;margin:1.35rem auto 0;color:var(--me-muted);font-size:1.08rem;line-height:1.68}.gb-sales-hero .me-btn{margin-top:2rem}.gb-trust{display:flex;justify-content:center;flex-wrap:wrap;gap:.75rem;margin-top:2rem}.gb-trust span{display:inline-flex;align-items:center;gap:.4rem;padding:.55rem .75rem;border:1px solid var(--me-line);border-radius:999px;background:var(--me-surface);color:var(--me-ink-2);font-size:.75rem}.gb-trust svg{width:1rem;color:var(--me-violet-2)}
.gb-offer{padding:var(--me-section) 0;background:var(--me-bg)}.gb-offer-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-top:2.5rem}.gb-offer-grid article{display:flex;flex-direction:column;padding:1.6rem;border:1px solid var(--me-line);border-radius:var(--me-r-xl);background:var(--me-surface)}.gb-offer-grid article:first-child{border-color:#aaa5ff;background:linear-gradient(145deg,#28245b,var(--me-surface))}.gb-product-label{align-self:flex-start;padding:.28rem .55rem;border:1px solid var(--me-line);border-radius:999px;color:var(--me-violet-2);font-size:.68rem;font-weight:650;letter-spacing:.1em;text-transform:uppercase}.gb-offer-grid h3{margin-top:1.5rem;font-size:1.25rem;font-weight:620;line-height:1.25}.gb-offer-grid article>p{margin-top:.7rem;color:var(--me-muted);font-size:.88rem;line-height:1.62}.gb-price{margin-top:1.5rem;padding-top:1.25rem;border-top:1px solid var(--me-line)}.gb-price strong,.gb-price small{display:block}.gb-price strong{font-size:1.55rem;letter-spacing:-.03em}.gb-price small{margin-top:.2rem;color:var(--me-muted);font-size:.72rem}.gb-offer-grid ul{display:grid;gap:.65rem;margin-top:1.2rem}.gb-offer-grid li{display:flex;gap:.55rem;color:var(--me-ink-2);font-size:.84rem;line-height:1.5}.gb-offer-grid li svg{flex:none;width:1rem;margin-top:.18rem;color:var(--me-mint)}.gb-offer-grid .me-btn{width:100%;margin-top:1.5rem}
.gb-included{padding:var(--me-section) 0;background:var(--me-bg-deep);border-block:1px solid var(--me-line)}.gb-included-grid{display:grid;grid-template-columns:.85fr 1.15fr;gap:clamp(2rem,6vw,6rem);align-items:start}.gb-included h2,.gb-buy-card h2{max-width:20ch;margin-top:.8rem;font-size:clamp(1.9rem,1.15rem + 2.5vw,2.8rem);font-weight:580;letter-spacing:-.035em;line-height:1.1}.gb-included>div>div>p:not(.me-eyebrow),.gb-buy-card p:not(.me-eyebrow){max-width:48ch;margin-top:1rem;color:var(--me-muted);line-height:1.65}.gb-included-list{border-top:1px solid var(--me-line)}.gb-included-list article{display:grid;grid-template-columns:2.25rem 1fr;gap:1rem;padding:1.35rem 0;border-bottom:1px solid var(--me-line)}.gb-included-list b{color:var(--me-violet-2);font-size:.72rem}.gb-included-list h3{font-size:1rem;font-weight:620}.gb-included-list p{margin-top:.35rem;color:var(--me-muted);font-size:.88rem;line-height:1.55}
.gb-why-buy{padding:var(--me-section) 0}.gb-buy-card{display:flex;align-items:center;justify-content:space-between;gap:2rem;padding:clamp(1.75rem,1rem + 2.5vw,3rem);border:1px solid var(--me-line);border-radius:var(--me-r-xl);background:var(--me-surface-2)}.gb-buy-card .me-btn{flex:none}.gb-faq{padding:0 0 var(--me-section)}.gb-faq-list{max-width:52rem;margin-top:2rem;border-top:1px solid var(--me-line)}.gb-faq-list details{padding:1.2rem 0;border-bottom:1px solid var(--me-line)}.gb-faq-list summary{cursor:pointer;color:var(--me-ink-2);font-size:1rem;font-weight:620}.gb-faq-list p{max-width:65ch;margin-top:.75rem;color:var(--me-muted);font-size:.9rem;line-height:1.65}
@media(max-width:52rem){.gb-offer-grid{grid-template-columns:1fr}.gb-included-grid{grid-template-columns:1fr}}@media(max-width:48rem){.gb-buy-card{align-items:flex-start;flex-direction:column}.gb-buy-card .me-btn{width:100%}}@media(max-width:30rem){.gb-sales-hero h1{font-size:2.35rem}.gb-trust{justify-content:flex-start}.gb-trust span{width:100%}}
`
