export const BRAND = {
  name: "Growth Believer",
  promise: "Practical digital resources for making progress in real life.",
  price: "₹499",
  cadence: "one-time digital product",
  guarantee: "Digital resources are delivered after the order is confirmed.",
} as const

/** Brand variables and reset shared by Growth Believer pages. */
export const brandStyles = `
.me-page{--me-bg:#151517;--me-bg-deep:#0f0f11;--me-surface:#1c1c1f;--me-surface-2:#212125;--me-surface-3:#27272c;--me-line:#74747f;--me-line-2:#a5a5b0;--me-ink:#f5f5f6;--me-ink-2:#d8d8dd;--me-muted:#b1b1b8;--me-quiet:#96969f;--me-violet:#8179ff;--me-violet-2:#b5b0ff;--me-mint:#77e0b4;--me-amber:#f1cf6d;--me-max:68rem;--me-gut:clamp(1.25rem,4vw,2.5rem);--me-section:clamp(4.5rem,2.4rem + 6vw,7.5rem);--me-r-sm:.5rem;--me-r-md:.875rem;--me-r-lg:1.375rem;--me-r-xl:1.875rem;--me-ease:cubic-bezier(.22,.85,.3,1);position:relative;min-height:100dvh;overflow-x:clip;background:var(--me-bg);color:var(--me-ink);font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:16px;line-height:1.6;letter-spacing:.002em;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
.me-page *{box-sizing:border-box}.me-page :where(h1,h2,h3,p,ul,hr){margin:0}.me-page :where(ul){padding:0;list-style:none}.me-page :where(hr){border:0}.me-page :where(svg){display:block;flex:none;width:1em;height:1em}.me-page :where(a){color:inherit;text-decoration:none}.me-page :where(a,summary,details){touch-action:manipulation}.me-page :focus-visible{outline:3px solid #d0ccff;outline-offset:3px}.me-wrap{width:min(100% - (var(--me-gut) * 2),var(--me-max));margin-inline:auto}.me-page :where([id]){scroll-margin-top:5.5rem}.me-page h1,.me-page h2,.me-page h3{text-wrap:balance}.me-page p{text-wrap:pretty}
`

/** Shared component styles. Page-specific composition stays beside its page. */
export const sharedStyles = `
.me-page :disabled{background:#4b4b55;color:#f5f5f6;border-color:#a5a5b0;cursor:not-allowed}dialog { margin: auto }
.me-logo{display:inline-flex;align-items:center;gap:.5rem;width:max-content;min-height:2.75rem;font-size:1rem;font-weight:700;letter-spacing:-.02em}.me-logo-mark{display:grid;place-items:center;width:1.625rem;height:1.625rem;border-radius:.5rem;background:linear-gradient(150deg,#fff,#c8c8d4);color:#1d1d2a;font-size:.8125rem;box-shadow:0 4px 12px -4px rgba(0,0,0,.8),inset 0 1px 0 rgba(255,255,255,.9);transition:transform .35s var(--me-ease)}.me-logo:hover .me-logo-mark{transform:rotate(-8deg) scale(1.06)}
.me-header{position:sticky;top:0;z-index:20;background:rgba(19,19,24,.94);backdrop-filter:blur(14px) saturate(140%);border-bottom:1px solid var(--me-line)}.me-nav{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:1rem;width:min(100% - (var(--me-gut) * 2),var(--me-max));min-height:4.25rem;margin-inline:auto}.me-nav-links{display:flex;justify-self:center;gap:.25rem}.me-nav-links a{display:inline-flex;align-items:center;gap:.3rem;min-height:2.75rem;padding-inline:.7rem;border-radius:.5rem;color:var(--me-ink-2);font-size:.875rem;font-weight:500;transition:color .24s var(--me-ease),background-color .24s var(--me-ease)}.me-nav-links a:hover,.me-login:hover{color:#fff;background:#35353b}.me-nav-actions{justify-self:end;display:flex;align-items:center;gap:.5rem}.me-login{display:inline-flex;align-items:center;min-height:2.75rem;padding-inline:.75rem;border-radius:.5rem;color:var(--me-ink-2);font-size:.875rem;font-weight:500}.me-signup{display:inline-flex;align-items:center;min-height:2.5rem;padding:.5rem 1.125rem;border:1px solid #fff;border-radius:999px;background:linear-gradient(180deg,#fff,#e6e6ec);color:#1c1c22;font-size:.875rem;font-weight:650;letter-spacing:-.005em;box-shadow:0 1px 2px rgba(0,0,0,.35)}
.me-btn{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;min-height:2.875rem;padding:.75rem 1.375rem;border:1px solid transparent;border-radius:var(--me-r-sm);font-size:.875rem;font-weight:650;letter-spacing:-.005em;line-height:1;white-space:nowrap;box-shadow:0 1px 2px rgba(0,0,0,.32),0 10px 26px -14px rgba(0,0,0,.85);transition:transform .28s var(--me-ease),box-shadow .28s var(--me-ease)}.me-btn:hover{transform:translateY(-2px)}.me-btn svg{width:1.0625rem;height:1.0625rem}.me-btn-light{background:linear-gradient(180deg,#fff,#e9e9ee);color:#1c1c22;border-color:#fff}.me-btn-violet{background:linear-gradient(180deg,#918bff,#5a50f4);color:#fff;border-color:#c5c1ff}.me-btn-ghost{background:#303037;color:#f5f5f6;border-color:var(--me-line);box-shadow:none}.me-section-heading h2{font-size:clamp(1.75rem,1.15rem + 2.3vw,2.5rem);font-weight:580;letter-spacing:-.03em;line-height:1.1}.me-section-heading>p:not(.me-eyebrow){max-width:52ch;margin-top:1rem;color:var(--me-muted);font-size:1rem;line-height:1.62}.me-eyebrow{color:var(--me-violet-2);font-size:.6875rem;font-weight:650;letter-spacing:.18em;line-height:1.4;text-transform:uppercase}
.me-footer{position:relative;padding:clamp(3.5rem,2rem + 4vw,5.5rem) 0 2rem;border-top:1px solid var(--me-line);background:linear-gradient(180deg,#141416,#101012)}.me-footer-top{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,2.9fr);gap:clamp(2rem,1rem + 2vw,3.25rem)}.me-footer-brand>p{max-width:26ch;margin-top:1rem;color:var(--me-muted);font-size:.8125rem;line-height:1.62}.me-footer-jump{display:inline-flex;align-items:center;gap:.4375rem;min-height:2.25rem;margin-top:1.5rem;padding:.4375rem .875rem;border:1px solid var(--me-line);border-radius:999px;background:#29292f;color:#f5f5f6;font-size:.8125rem;font-weight:550}.me-footer-cols{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:2rem 1.25rem}.me-footer-cols h2{color:var(--me-muted);font-size:.6875rem;font-weight:650;letter-spacing:.16em;line-height:1.4;text-transform:uppercase}.me-footer-cols ul{display:grid;gap:.125rem;margin-top:1.125rem}.me-footer-cols a{display:inline-flex;align-items:center;min-height:2rem;color:var(--me-ink-2);font-size:.8125rem;line-height:1.45}.me-footer-cols a:hover,.me-footer-legal a:hover{color:#fff}.me-footer-bottom{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:.75rem 1.5rem;margin-top:clamp(2.75rem,2rem + 2vw,4rem);padding-top:1.5rem;border-top:1px solid var(--me-line);color:var(--me-muted);font-size:.8125rem}.me-footer-legal{display:flex;flex-wrap:wrap;gap:.375rem 1.5rem}.me-footer-legal a{display:inline-flex;align-items:center;min-height:2rem;color:var(--me-ink-2)}
@media(max-width:48rem){.me-nav{grid-template-columns:1fr auto}.me-nav-links{display:none}.me-footer-top{grid-template-columns:1fr;gap:2.5rem}.me-footer-cols{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:23.5rem){.me-page{--me-gut:.875rem}.me-login{display:none}.me-footer-cols{grid-template-columns:1fr}}
.me-btn-violet{background:linear-gradient(180deg,#4f47c7,#37308f)}.me-btn-ghost{border-color:#a5a5b0}
/* kit patch 2026-09-08: cap section rhythm so two adjacent bands (e.g. a hero's
   bottom padding and the next band's top padding, both often using
   --me-section) don't stack into a dead-space gap between them. */
.me-page{--me-section:clamp(3.5rem,7vw,6.5rem)}
`
